openapi: 3.0.0
info:

  title: Tshirtstore api
  description: a project to explore creating api for ecom app
  version: 1.0.0
  contact:
    email: nikhilkumarpasumarthi14@gmail.com


#this is a dropdown model
# servers:
#   - url: https://localhost:4000/api/v1
#     description: an local server -secure one

#   - url: http://localhost:4000/api/v1
#     description: an local server - regular one

# this is a parameterized model
servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - https
          - http
        default: http 


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /dummy:
    get:
      tags:
        - Home
      summary: it is a get request of lco
      responses:
        200:
          description: all good
          content:
            application/json:
              schema:
                type: string
                example: "my string"
              items:
                type: string
                example: "my string type"
        
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: string
                example: "my string "
              items:
                type: string
                example: "my string type"
        
        500:
          description: internal server error
          content: 
            application/json:
              schema:
                type: string
                example: "my string"
              items:
                type: string
                example: "my string type"

